name: trigger-gitlab-ci
run-name: ${{ github.event_name }} triggered by ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  trigger-gitlab-ci:
      runs-on: ubuntu-latest
      steps:
          - name: Trigger CI
            run: curl -X POST --fail -F token=${{ secrets.trigger_gitlab_ci }} -F ref=main https://gitlab.com/api/v4/projects/54782732/trigger/pipeline
